### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by jdittrich** [Slevinski/signwriting_2010_tools#2]
**Story:** As a potential contributor I would like to know the license of the project so I know under which license my contributions will be used. 

**Current state:** The license is not clear to me. There are some mentions of "license" or "copyright" in the readme, but they seem to refer the the license of the fonts. 

**Possible solutions:** Declare a license that is compatible with the code reused in the repository. If there are multiple sub-parts with different licenses, tell this in the readme so that people can look for the specific licenses.

**Comment by Slevinski** [comment]
This project is currently licensed under the GPL 2 or later.  The python script files contain a license statement.  

I have moved away from the GPL to the MIT license for my most recent project.  I will release this project under the MIT license as well.

Early January 2018, I will cleanup this project for licenses in the README and add project tags and downloads.

Thanks for the comments.

**Comment by Slevinski** [comment]
I have updated the license to MIT by adding a license file, updating the README, and updating the individual python files.

The font SVG source is parts of another project (signwriting_2010_fonts).  The other project is licensed under the OFL. I can clarify further if it is still unclear.
